# Generated by Django 5.0.6 on 2024-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10000)),
                ('title', models.CharField(max_length=10000)),
                ('date', models.CharField(max_length=4000)),
                ('blogger', models.CharField(max_length=4000)),
            ],
        ),
    ]
