# Generated by Django 5.0.6 on 2024-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
